// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	int n = Integer.parseInt(args[0]);
	for(int i = 0; i >= n; i++) {
		System.out.println(n);
		if (n>0.5) {
		
		}
		
	}    
	}
}
//להשתמש בfor 